//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Input : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Input()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""5K"",
            ""id"": ""7330c4c5-18b4-4afe-ab85-c5d41eec84e8"",
            ""actions"": [
                {
                    ""name"": ""Key0"",
                    ""type"": ""Button"",
                    ""id"": ""3648b498-e4c9-4612-8847-20966766937a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key1"",
                    ""type"": ""Button"",
                    ""id"": ""541b1717-fe2e-46f3-a4b9-2fd2f8c3295e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key2"",
                    ""type"": ""Button"",
                    ""id"": ""402c578d-ffdd-462d-8794-5c7936b90065"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key3"",
                    ""type"": ""Button"",
                    ""id"": ""c74b2d46-7ca6-411c-9fe8-b83ff3801d81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Key4"",
                    ""type"": ""Button"",
                    ""id"": ""73f6eb7c-774c-4f2b-9d99-4f94a7eb5803"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2c69a595-d4a4-45fb-ae06-a1c506656428"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a31d11b-f35a-427a-9391-69f67981b3d2"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a9d7912-525f-4bb2-b53d-faa3af2997e3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f22639a6-fa87-4498-be6c-a9c1c5e1ccb8"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a2e75a9-f249-4732-bbec-59fd34a11d17"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Key4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // 5K
        m__5K = asset.FindActionMap("5K", throwIfNotFound: true);
        m__5K_Key0 = m__5K.FindAction("Key0", throwIfNotFound: true);
        m__5K_Key1 = m__5K.FindAction("Key1", throwIfNotFound: true);
        m__5K_Key2 = m__5K.FindAction("Key2", throwIfNotFound: true);
        m__5K_Key3 = m__5K.FindAction("Key3", throwIfNotFound: true);
        m__5K_Key4 = m__5K.FindAction("Key4", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // 5K
    private readonly InputActionMap m__5K;
    private I_5KActions m__5KActionsCallbackInterface;
    private readonly InputAction m__5K_Key0;
    private readonly InputAction m__5K_Key1;
    private readonly InputAction m__5K_Key2;
    private readonly InputAction m__5K_Key3;
    private readonly InputAction m__5K_Key4;
    public struct _5KActions
    {
        private @Input m_Wrapper;
        public _5KActions(@Input wrapper) { m_Wrapper = wrapper; }
        public InputAction @Key0 => m_Wrapper.m__5K_Key0;
        public InputAction @Key1 => m_Wrapper.m__5K_Key1;
        public InputAction @Key2 => m_Wrapper.m__5K_Key2;
        public InputAction @Key3 => m_Wrapper.m__5K_Key3;
        public InputAction @Key4 => m_Wrapper.m__5K_Key4;
        public InputActionMap Get() { return m_Wrapper.m__5K; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(_5KActions set) { return set.Get(); }
        public void SetCallbacks(I_5KActions instance)
        {
            if (m_Wrapper.m__5KActionsCallbackInterface != null)
            {
                @Key0.started -= m_Wrapper.m__5KActionsCallbackInterface.OnKey0;
                @Key0.performed -= m_Wrapper.m__5KActionsCallbackInterface.OnKey0;
                @Key0.canceled -= m_Wrapper.m__5KActionsCallbackInterface.OnKey0;
                @Key1.started -= m_Wrapper.m__5KActionsCallbackInterface.OnKey1;
                @Key1.performed -= m_Wrapper.m__5KActionsCallbackInterface.OnKey1;
                @Key1.canceled -= m_Wrapper.m__5KActionsCallbackInterface.OnKey1;
                @Key2.started -= m_Wrapper.m__5KActionsCallbackInterface.OnKey2;
                @Key2.performed -= m_Wrapper.m__5KActionsCallbackInterface.OnKey2;
                @Key2.canceled -= m_Wrapper.m__5KActionsCallbackInterface.OnKey2;
                @Key3.started -= m_Wrapper.m__5KActionsCallbackInterface.OnKey3;
                @Key3.performed -= m_Wrapper.m__5KActionsCallbackInterface.OnKey3;
                @Key3.canceled -= m_Wrapper.m__5KActionsCallbackInterface.OnKey3;
                @Key4.started -= m_Wrapper.m__5KActionsCallbackInterface.OnKey4;
                @Key4.performed -= m_Wrapper.m__5KActionsCallbackInterface.OnKey4;
                @Key4.canceled -= m_Wrapper.m__5KActionsCallbackInterface.OnKey4;
            }
            m_Wrapper.m__5KActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Key0.started += instance.OnKey0;
                @Key0.performed += instance.OnKey0;
                @Key0.canceled += instance.OnKey0;
                @Key1.started += instance.OnKey1;
                @Key1.performed += instance.OnKey1;
                @Key1.canceled += instance.OnKey1;
                @Key2.started += instance.OnKey2;
                @Key2.performed += instance.OnKey2;
                @Key2.canceled += instance.OnKey2;
                @Key3.started += instance.OnKey3;
                @Key3.performed += instance.OnKey3;
                @Key3.canceled += instance.OnKey3;
                @Key4.started += instance.OnKey4;
                @Key4.performed += instance.OnKey4;
                @Key4.canceled += instance.OnKey4;
            }
        }
    }
    public _5KActions @_5K => new _5KActions(this);
    public interface I_5KActions
    {
        void OnKey0(InputAction.CallbackContext context);
        void OnKey1(InputAction.CallbackContext context);
        void OnKey2(InputAction.CallbackContext context);
        void OnKey3(InputAction.CallbackContext context);
        void OnKey4(InputAction.CallbackContext context);
    }
}
